---
- name: Check GPG keyring file
  stat:
    path: /usr/share/keyrings/elasticsearch-keyring.gpg
  register: keyring_status

- name: Download Elastic GPG Key
  command: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch
  register: gpg_key_output
  when: not keyring_status.stat.exists

- name: Import Elastic GPG Key
  command: gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    stdin: "{{ gpg_key_output.stdout }}"
  when: not keyring_status.stat.exists

- name: Add Elastic APT Repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main'
  when: not keyring_status.stat.exists

- name: Update Package List
  apt:
    update_cache: yes
  when: not keyring_status.stat.exists

- name: Install Kibana
  apt:
    name: kibana
    state: present

- name: Enable Kibana Service
  systemd:
    name: kibana
    enabled: yes
    daemon-reload: true

- name: Copy Kibana Configuration
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"  

- name: Start Kibana Service
  systemd:
    name: kibana
    state: started

- name: restart Kibana
  systemd:
    name: kibana
    state: restarted
