---
- name: Configure NTP server
  template:
    src: ntp.j2
    dest: /etc/ntp.conf

- name: Create a cron job for time synchronization
  cron:
    name: Sync system time
    job: "0 0 * * * /usr/sbin/ntpdate -s {{ntp_server}}" 
    user: root  